PLejeune\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: PLejeune\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
        roles:
            type: array
        titre:
            type: string
            length: 255
            nullable : true
        firstname:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dateNaissance:
            type: datetime
            column: date_naissance
            nullable: true
        dateRegistration:
            type: datetime
            column: date_registration
        dateValidation:
            type: datetime
            nullable: true
            column: date_validation
        facebook:
            type: string
            length: 255
            nullable : true
        twitter:
            type: string
            length: 255
            nullable : true
        instagram:
            type: string
            length: 255
            nullable : true
        youtube:
            type: string
            length: 255
            nullable : true
        twitch:
            type: string
            length: 255
            nullable : true
        avatar:
            type: string
            length: 255
            nullable : true
        token:
            type: string
            length: 255
            nullable : true
        token_type:
            type: string
            length: 255
            nullable : true
        token_date:
            type: datetime
            nullable : true
        enable:
            type: boolean
    lifecycleCallbacks: {  }
